### ISSUE TITLE
Links to docs are broken

### ISSUE THREAD

**Issue by mourner** [skypackjs/package-check#10]
Not sure if this is the right place to report this, but links to docs about package checks seem broken, e.g. this one is 404 https://docs.skypack.dev/package-authors/package-checks

**Comment by FredKSchott** [comment]
Shoot, I did that! Looks like gitbook doesn't let you customize the full URL, even if we wanted to set a custom slug. I'll update the catalog links instead.

**Comment by FredKSchott** [comment]
Fixed! thanks for filing
