### ISSUE TITLE
Throw if no `README.md` file exists

### ISSUE THREAD

**Issue by gr2m** [skypackjs/package-check#2]
```
➜  ls
index.esm.js      index.js          node_modules      package-lock.json package.json
➜  npx package-check
ENOENT: no such file or directory, open '/Users/gregor/Projects/repro/skypackjs/2/README.md'
```

Simple repro:

```
git clone git clone git@gist.github.com:1c6fe1a81093651c4f2d0305dccdfb79.git skypack-repro-2
cd skypack-repro-2
npm install
npx package-check
```

**Comment by stramel** [comment]
I noticed this as well when checking the code. Seems like we should probably only read the `README.md` when it is in the README check as well

**Comment by gr2m** [comment]
we currently also check for `README.md` specifically, but many more extensions are supported:
https://github.com/github/markup/blob/master/README.md#markups

**Comment by FredKSchott** [comment]
Fixed in https://github.com/skypackjs/package-check/commit/e538ccd288b44e5a3fe05c241498a41a42ba03ee
