### ISSUE TITLE
"Check failed:  Export Map" if "module" key is present

### ISSUE THREAD

**Issue by gr2m** [skypackjs/package-check#3]
The docs currently state

> ESM stands for *ES Modules* a.k.a [JavaScript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules), which is the new standard for JavaScript. This check ensures that at least one of the following conditions are met:
>
> -   **Recommended:** Your `package.json` contains an ESM export, e.g.:`"exports": { "import": "./path/to/entry.js" }` or `"exports": { ".": { "import": "..." } }` ([docs](https://nodejs.org/api/packages.html#packages_approach_1_use_an_es_module_wrapper))
> -   Your `package.json` contains `"type": "module"` ([docs](https://nodejs.org/api/packages.html#packages_type))
> -   Your `package.json` contains a `"module": "./path/to/entry.js"` entry (not officially supported by Node.js, but [an organic community convention](https://github.com/rollup/rollup/wiki/pkg.module) we respect).
> -   *Supported, but not recommended:* Your `package.json` contains a `"main"` field that ends in `.mjs` ([this mimics Node behavior](https://nodejs.org/api/packages.html#packages_determining_module_system)). We'd recommend adding `"exports.import"` as well if this is your only indicator.

When my package does have the `"type": "module"` however, I still get the error

```
➜  cat package.json 
{
  "name": "skypack-package-check",
  "version": "1.0.0",
  "main": "index.js",
  "module": "index.esm.js",
  "license": "MIT",
  "devDependencies": {
    "@skypack/package-check": "^0.1.0"
  }
}
➜  npx package-check
Check failed:  Export Map
How to fix:  https://docs.skypack.dev/package-authors/package-checks#export-map
```

Adding the `"module"` key is what `pika build` currently does by default, so a lot of folks coming from Pika who might be interested in this will be affected. Including yours truly ✌🏼 

Repro

```
git clone git clone git@gist.github.com:ea47e72a1f5b8ec2a7eb66e5701eefd5.git skypack-repro-3
cd skypack-repro-3
npm install
npx package-check
```

**Comment by FredKSchott** [comment]
The idea is that you should run this in the directory of the package that you're deploying. In this case, that would be `./pkg`. Let me add a `--cwd` command line arg

**Comment by FredKSchott** [comment]
But for now, this should work:

```
git clone git@gist.github.com:ea47e72a1f5b8ec2a7eb66e5701eefd5.git skypack-repro-3
cd skypack-repro-3
npm install
cd pkg && npx package-check
```

**Comment by FredKSchott** [comment]
Ah wait, I misread this. I thought that it was the ESM pass that was failing, and not the export map check. This is a UI problem on our end, we don't show that you've already passed the ESM check.

Your larger issue is that @pika/pack was created before export maps existed, and doesn't create export maps

**Comment by FredKSchott** [comment]
Improved error output and added a `cwd` flag
