### ISSUE TITLE
Fails if types are missing

### ISSUE THREAD

**Issue by gr2m** [skypackjs/package-check#6]
Is this intended?

```
➜  ls
README.md         index.js          node_modules      package-lock.json package.json
➜  npx package-check
Check failed:  TypeScript Types
How to fix:  https://docs.skypack.dev/package-authors/package-checks#types
```

I would expect to only share the error if there are index.d.ts files, but no `"types"` key is present in package.json

**Comment by stramel** [comment]
I believe that it works still if no `types` key is present but there is an `index.d.ts` file present.

**Comment by FredKSchott** [comment]
This is intended behavior, if a bit controversial. We're taking the stance that a perfect package ships TypeScript types. **Over half of the JS community writes or has written TypeScript before** according to [State of JS Survey, 2019](https://2019.stateofjs.com/javascript-flavors/typescript/). That means that shipping types is a way to improve the development experience for over half of the JS ecosystem.  

Note that this is NOT saying that a perfect package is WRITTEN in TypeScript. You can write your package however you like, but including TypeScript types in your package manifest is the only way to pass this quality check.

**Comment by FredKSchott** [comment]
A couple of related comments / questions: 

1. **"I don't care about ts types"** - You should definitely be able to opt-out / ignore any check in this CLI. You won't get a 100%, but we can still pass as far as the CI/testing tool is concerned.
1. **"I don't ship types, but a DefinitelyTyped @types/* packages exists"** - That's still an extra step for your users to go through (and commonly are only partially defined). It's better, but not PERFECT (and we're really talking about how to be perfect, here). We do want to show that difference in our skypack.dev quality score and I'd love if we could show that difference here, but to be considered "perfect" ya gotta ship and maintain your own types. 
3. **"I include types at index.d.ts, so I don't need a "types" package.json entrypoint"** - Automated tooling like ours can't tell this without installing your package tarball, unpacking it to a file system, and then reading your package contents. Again, to be PERFECT, you should make sure that all automated tools (us., npmjs.com search, yarn/algolia search, TypeScript.com search, etc) can all detect and show this to their users.

**Comment by FredKSchott** [comment]
A better error message added here: 787a9c3
