### ISSUE TITLE
package.json: change exports.import to "./esm-wrapper.mjs"

### ISSUE THREAD

**Issue by gr2m** [skypackjs/package-check#7]
There is currently no `index.esm.mjs` file.

https://github.com/skypackjs/package-check/blob/c1ed977ad1828329ac28f3433eed55083743d7b2/package.json#L8

I assume it was meant to be `"./esm-wrapper.mjs"`?

**Comment by FredKSchott** [comment]
fixed, but lets turn this into a larger feature: `package-check` should be able to validate that each pointed to file exists.

**Comment by gr2m** [comment]
I think there is a misunderstanding? This is not about a bug or feature, it's about its `package-check`'s own source code

**Comment by FredKSchott** [comment]
Ah sorry, I made the fix but forgot to push. All fixed now

**Comment by gr2m** [comment]
fixed via 619e650466e54b617a9fd7cb9755c898d049d662
